### ISSUE TITLE
Missing support for eip-1898: eth_call not working

### ISSUE THREAD

**Issue by dahof1** [iotaledger/wasp-legacy#1153] opened 2022-07-15 14:24 UTC
Version: 0.3.0 (commit: f59142ffe5e1674e9e5740b11c9a16c1a4e17192)

The following call
`
curl <RPC-URL> -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x95d89b41","gas":"0x0","to":"0x2f33855178d3c962b9a3092e9e6f4a91a82a7968"},{"blockHash" :"0xc6389ba216dcb791605708e1908a2856aeb65c1e02a7489a820f0168ed0bc6b4"}],"id":258}'
`

Results in:
`{"jsonrpc":"2.0","id":258,"error":{"code":-32000,"message":"CallViewExternal: unsupported operation"}} `

This is similar to #486 and #508 which were already fixed.

**Comment by dessaya** [comment] 2022-07-20 21:51
@dahof1 

Currently our EVM layer only supports calling functions on the latest block.

Your call includes `{"blockHash" :"0xc6389ba216dcb791605708e1908a2856aeb65c1e02a7489a820f0168ed0bc6b4"}` which is probably not the latest block?

**Comment by dahof1** [comment] 2022-08-11 05:36
Hi @dessaya ,

yes exactly, its not the latest block. Is it possibly to extend the functionality to support different hashes? This would be ideally to traverse the blocks with eth_call.

**Comment by dessaya** [comment] 2022-08-11 18:20
We are working on that @dahof1. The design of IOTA Smart Contracts is vastly different from EVM, so things like this are hard to implement. We plan to add support for querying past blocks but probably not in the near future.

**Comment by dahof1** [comment] 2022-08-15 19:01
Hi @dessaya,
thanks for the info! so i guess a lot things changed under the hood because i slightly remember that the eth_call for different hashes worked already (in past develop version). but i am not sure :)

**Comment by dessaya** [comment] 2022-08-15 21:29
That's right, we changed the implementation significantly in order to provide an integration between EVM and ISC. Among other things, we don't store the state of previous blocks anymore (although it is technically possible to re-execute all blocks since genesis, we are working on something like that).
More information about the current implementation here: https://github.com/iotaledger/wasp/blob/develop/documentation/docs/guide/evm/compatibility.md

**Comment by dessaya** [comment] 2022-11-24 22:16
This is a duplicate of #1399 ?

**Closed as completed** 2023-12-12 11:39 UTC
