### ISSUE TITLE
Refactor: remove "mint tokens" param in foundry creation

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/wasp-legacy#3267] opened 2024-02-12 13:11 UTC
**Describe the bug**

When I try to create a foundry with `foundryCreateNew` and I specify mintetTokens it seems to ignore that.
So creating foundry with circulating supply 0 works. But as soon as I try to create the foundry with some minted token it fails.

**To Reproduce**

1. Deploy contract 
```solidtiy
// SPDX-License-Identifier: MIT
 pragma solidity ^0.8.0;
 import "@iota/iscmagic/ISC.sol";
 contract CreateFoundry {
     event CreatedFoundry(uint foundrySN);
     function createFoundry(uint _mintedTokens, uint _meltedTokens, uint _maximumSupply) public payable {
         NativeTokenScheme memory nativeTokenScheme = NativeTokenScheme({
             mintedTokens: _mintedTokens,
             meltedTokens: _meltedTokens,
             maximumSupply: _maximumSupply
         });
         ISCAssets memory allowance = ISCAssets({
             baseTokens: 500_000,
             nativeTokens: new NativeToken[](0),
             nfts: new NFTID[](0)
         });
         uint foundrySN = ISC.accounts.foundryCreateNew(nativeTokenScheme, allowance);
         emit CreatedFoundry(foundrySN);
     }
 }
```
2. Interact with Contract by calling method createFoundry(0,0,100)
3. Success
4. Interact with Contract by calling method createFoundry(100,0,100)
5. It still creates a foundry without any basic token output and no circulation supply

**Expected behavior**

Calling `createFoundry(100,0,100)` should create a block with a foundry output and a basic output containing 100 native token.
Like this: https://explorer.shimmer.network/testnet/block/0x077fc366f15af0ec1623392f534e3781a804b090ebfde8f4090821b4f1ba57e4

**Network and versioning**
 - Type of L1 network: Private Tangle
 - Type of Wasp chain: Private chain
 - Interaction method: JSON/RPC HTTP
 - Interaction software: hardhat
 - Version of Wasp: v1.0.2-alpha.4

**Additional context**

**Comment by jorgemmsilva** [comment] 2024-06-11 10:59
This is not supported by design. We should remove the parameter from the function

**Comment by jorgemmsilva** [comment] 2024-07-01 13:14
coming back to this issue, I realize it's not a parameter that we provide, but actually part of the `NativeTokenScheme` type. Not much we can do here. Closing this.

**Closed as completed by jorgemmsilva** 2024-07-01 13:14 UTC
Labels: bug

**Comment by Dr-Electron** [comment] 2024-07-02 14:18
But you could still hide it from the public interfaces, no? 
So for example do the following:
```diff
- ISC.accounts.foundryCreateNew(NativeTokenScheme nativeTokenScheme, ISCAllowance allowance)
+ ISC.accounts.foundryCreateNew(uint maxSupply, ISCAllowance allowance)
```
If the other parameters can't be set, they should not be available. Don't you think?
